---
collections:
  - name: ansible.netcommon
    source: https://galaxy.ansible.com
    version: 3.0.1
  - name: ansible.posix
    source: https://galaxy.ansible.com
    version: 1.4.0
  - name: community.general
    source: https://galaxy.ansible.com
    version: 5.1.1
  - name: openstack.cloud
    source: https://galaxy.ansible.com
    version: 1.8.0
